# Generated by Django 3.0.7 on 2020-06-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='', upload_to='Items/'),
            preserve_default=False,
        ),
    ]
