# Generated by Django 3.0.7 on 2020-06-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200614_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_image', models.ImageField(upload_to='Popular_Items/')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
