# Generated by Django 3.0.7 on 2020-06-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_popularitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopularItems',
            new_name='PopularItem',
        ),
    ]
