# Generated by Django 3.0.7 on 2020-06-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200614_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='ChoiceItem',
        ),
    ]
